version: "3.9"
services:
  php-fpm81:
    build:
      context: "./"
      dockerfile: "./docker/php-fpm81/Dockerfile"
    volumes:
      - ./app:/var/www
    working_dir: /var/www

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php-fpm81
