version: "3.9"
services:
  php-fpm81:
    build:
      context: "./"
      dockerfile: "./docker/php-fpm81/Dockerfile"
    volumes:
      - ./app:/var/www
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /var/www

  nginx:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php-fpm81

  mysql:
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3326:3306

volumes:
  mysql-data:
