version: "3.9"
services:
  php-fpm81:
    container_name: ${PROJECT_NAME}_${APP_NAME}_php-fpm81
    build:
      context: "./"
      dockerfile: "./docker/php-fpm81/Dockerfile"
    volumes:
      - ./app:/var/www
    links:
      - mysql
    depends_on:
      - mysql
    working_dir: /var/www
    networks:
      - digden_network

  nginx:
    image: nginx:1.20-alpine
    container_name: ${PROJECT_NAME}_${APP_NAME}_nginx
    ports:
      - 8080:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - php-fpm81
    networks:
      - digden_network

  mysql:
    container_name: ${PROJECT_NAME}_${APP_NAME}_mysql
    build: ./docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3326:3306
    networks:
      - digden_network

volumes:
  mysql-data:

networks:
  digden_network:
    external: true
